name: Demo Secrets
on:
  push:
    branches:
      - main

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar segredo
        run: echo "A chave secreta é ${{ secrets.API_KEY }}"
